# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import monsters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=monsters.models.random_name, max_length=30)),
                ('health', models.IntegerField(default=monsters.models.random_stats)),
                ('defense', models.IntegerField(default=monsters.models.random_stats)),
                ('attack', models.IntegerField(default=monsters.models.random_stats)),
                ('monster_type', models.CharField(default=monsters.models.random_type, max_length=100)),
                ('unique_id', models.IntegerField(default=0)),
                ('img_file', models.ImageField(upload_to='')),
                ('monster_story', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
