# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='monster',
            name='defense',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(default='Skeleton', max_length=100),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='Jose', max_length=30),
        ),
        migrations.AlterField(
            model_name='monster',
            name='unique_id',
            field=models.CharField(default=-351518328005505787, max_length=150),
        ),
    ]
