# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_auto_20171218_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='Barbara', max_length=30),
        ),
        migrations.AlterField(
            model_name='monster',
            name='unique_id',
            field=models.CharField(default=1173534653241406271, max_length=150),
        ),
    ]
