# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20171218_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='monster',
            name='defense',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(default='Zombie', max_length=100),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='Andrea', max_length=30),
        ),
        migrations.AlterField(
            model_name='monster',
            name='unique_id',
            field=models.CharField(default=1705383070707685180, max_length=150),
        ),
    ]
