# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20171219_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='monster',
            name='img_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
