# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0004_auto_20171219_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
    ]
