# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_monster_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='monster_story',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
