# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0007_auto_20171220_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_story',
            field=models.TextField(blank=True),
        ),
    ]
